var mountain = { name: "K2" };
var animal = { name: "Crocs" };
var something = { name: "Something" };
var gibberish = { name: "dnfslj" };
var language = { name: "Urdu" };
console.log(mountain);
console.log(animal);
console.log(something);
console.log(gibberish);
console.log(language);
