var str1 = 'hello';
var str2 = 'world';
console.log(str1 == str2);
console.log(str1 != str2);
var upperCaseStr = 'HELLO';
var lowerCaseStr = 'hello';
console.log(upperCaseStr.toLowerCase() == lowerCaseStr);
var num1 = 890;
var num2 = 500;
console.log(num1 == num2);
console.log(num1 != num2);
console.log(num1 > num2);
console.log(num1 < num2);
console.log(num1 >= num2);
console.log(num1 <= num2);
var condition1 = true;
var condition2 = false;
console.log(condition1 && condition2);
console.log(condition1 || condition2);
var fruits = ['tikka', 'mango', 'salt'];
console.log(fruits.indexOf('sugar') !== -1);
console.log(fruits.indexOf('mango') === -1);
